export const INCOME_CATEGORIES = {
  salary: "Salary & Wages",
  bonus: "Bonuses & Commissions",
  investment: "Investment Income",
  rental: "Rental Income",
  business: "Business Income",
  gifts: "Gifts Received",
  tax_refund: "Tax Refunds",
  interest: "Interest Income",
  dividends: "Dividends",
  side_gig: "Side Gig & Freelance",
  pension: "Pension & Retirement",
  social_security: "Social Security",
  reimbursement: "Reimbursements",
  other_income: "Other Income",
} as const;

export const EXPENSE_CATEGORIES = {
  housing: "Housing & Rent",
  mortgage: "Mortgage/Bond",
  utilities: "Utilities",
  groceries: "Groceries",
  dining: "Dining Out",
  transportation: "Transportation",
  insurance: "Insurance",
  healthcare: "Healthcare",
  education: "Education",
  entertainment: "Entertainment",
  clothing: "Clothing & Apparel",
  personal_care: "Personal Care",
  travel: "Travel",
  debt_payment: "Debt Payments",
  subscriptions: "Subscriptions",
  gifts_donations: "Gifts & Donations",
  childcare: "Childcare",
  pet_expenses: "Pet Expenses",
  home_maintenance: "Home Maintenance",
  taxes: "Taxes",
  investments: "Investment Purchases",
  savings: "Savings Contributions",
  electronics: "Electronics & Gadgets",
  hobbies: "Hobbies & Recreation",
  other_expenses: "Other Expenses",
} as const;
